// Speech: pre-recorded MP3 clips (public/audio, generated by scripts/tts.py with Piper voices) so
// audio works everywhere — including phone webviews that have no speechSynthesis. Falls back to the
// Web Speech API only for texts without a clip.
import { create } from 'zustand';
import manifest from '../audio/manifest.json';
import { getTerm } from './glossary';
import type { Lang } from './types';

export type Voice = 'rosa' | 'mike_es' | 'en';

export interface SpeechItem {
  text: string;
  lang: Lang;
  /** Spanish voice to use (default Rosa). English always uses the 'en' voice. */
  voice?: Voice;
}

const clips = new Set<string>(manifest as string[]);

/** Markup → plain speakable text. Keep identical to scripts/speech-export.mjs. */
export function plainText(text: string): string {
  return text
    .replace(/\[\[([a-z0-9_-]+)(?:\|([^\]]*))?\]\]/gi, (_, id: string, disp?: string) => disp || getTerm(id)?.term || id)
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/[“”]/g, '"')
    .trim();
}

/** FNV-1a 32-bit over UTF-8 of "voice|text". Keep identical to scripts/speech-export.mjs. */
export function audioKey(voice: Voice, text: string): string {
  let h = 0x811c9dc5;
  for (const b of new TextEncoder().encode(`${voice}|${text}`)) {
    h ^= b;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

export function clipFor(item: SpeechItem): string | null {
  const voice: Voice = item.lang === 'en' ? 'en' : (item.voice ?? 'rosa');
  const key = audioKey(voice, plainText(item.text));
  return clips.has(key) ? `${import.meta.env.BASE_URL}audio/${key}.mp3` : null;
}

// ---- playback state (drives the animated 🔊 buttons) ----
interface SpeechState {
  /** id of the control that started the current playback (null = silent) */
  playing: string | null;
  /** last playback could not produce any sound */
  failed: boolean;
}
export const useSpeech = create<SpeechState>()(() => ({ playing: null, failed: false }));

const synthSupported = () => typeof window !== 'undefined' && 'speechSynthesis' in window;
export const speechSupported = () => true; // clips always available; kept for callers

let audio: HTMLAudioElement | null = null;
let queue: SpeechItem[] = [];
let token = 0;

function getAudio() {
  if (!audio && typeof Audio !== 'undefined') {
    audio = new Audio();
    audio.preload = 'auto';
  }
  return audio;
}

export function stopSpeech() {
  token++;
  queue = [];
  const a = getAudio();
  if (a) {
    a.pause();
    a.removeAttribute('src');
  }
  if (synthSupported()) window.speechSynthesis.cancel();
  useSpeech.setState({ playing: null });
}

function done(run: number) {
  if (run === token) useSpeech.setState({ playing: null });
}

function playNext(run: number) {
  if (run !== token) return;
  const item = queue.shift();
  if (!item) return done(run);
  const url = clipFor(item);
  if (url) {
    const a = getAudio();
    if (!a) return playNext(run);
    a.onended = () => playNext(run);
    a.onerror = () => fallback(item, run);
    a.src = url;
    a.play().catch(() => fallback(item, run));
    return;
  }
  fallback(item, run);
}

function fallback(item: SpeechItem, run: number) {
  if (run !== token) return;
  if (!synthSupported()) {
    useSpeech.setState({ failed: true });
    return playNext(run);
  }
  const u = new SpeechSynthesisUtterance(plainText(item.text));
  u.lang = item.lang === 'en' ? 'en-US' : 'es-US';
  u.rate = item.lang === 'en' ? 0.9 : 1;
  u.onend = () => playNext(run);
  u.onerror = () => playNext(run);
  window.speechSynthesis.speak(u);
}

/** Speaks fragments in order (each in its own language/voice). Cancels what was playing. */
export function speakSequence(items: SpeechItem[], source = 'any') {
  stopSpeech();
  const run = token;
  queue = items.filter((i) => i.text.trim());
  if (!queue.length) return;
  useSpeech.setState({ playing: source, failed: false });
  playNext(run);
}

export function speakEnglish(text: string, source = 'term') {
  speakSequence([{ text, lang: 'en' }], source);
}
